### ISSUE TITLE
Essa biblioteca me deixou perdido como usá-la.

### ISSUE THREAD

**Issue by cpdrenato** [reinaldoborges/rb-sphinx-hmac-zf2#1]
Essa biblioteca me deixou perdido como usá-la.
Tem algum tutorial que ajuda melhor implanta-la no zend Framework e apigility?

**Comment by reinaldoborges** [comment]
Olá. Veja exemplo nesse outro projeto:
https://github.com/reinaldoborges/rb-sphinx-hmac-zf2-examples-server
